apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Parser docker
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name opensearch
        Match *
        Host search-status-page-secrets-ei-wlyuj5tryf3rbhx3ukbjukwcti.us-east-1.es.amazonaws.com
        Port 443
        TLS On
        Index fluentbit
        HTTP_User ELADitai2025
        HTTP_Passwd ELADitai@2025
        AWS_Auth On
        AWS_Region us-east-1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"fluent-bit.conf":"[SERVICE]\n    Flush         1\n    Daemon        Off\n    Log_Level     info\n    Parsers_File  parsers.conf\n    HTTP_Server   On\n    HTTP_Listen   0.0.0.0\n    HTTP_Port     2020\n    Health_Check  On\n\n[INPUT]\n    Name tail\n    Path /var/log/containers/*.log\n    Tag kube.*\n    Parser docker\n    DB /var/log/flb_kube.db\n    Mem_Buf_Limit 5MB\n    Skip_Long_Lines On\n\n[FILTER]\n    Name kubernetes\n    Match kube.*\n    Merge_Log On\n    Keep_Log Off\n    K8S-Logging.Parser On\n    K8S-Logging.Exclude On\n\n[OUTPUT]\n    Name opensearch\n    Match *\n    Host ${OPENSEARCH_HOST}\n    Port 443\n    TLS On\n    Index fluentbit\n    HTTP_User ${OPENSEARCH_USER}\n    HTTP_Passwd ${OPENSEARCH_PASS}\n    AWS_Auth On\n    AWS_Region us-east-1\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"fluentbit-custom-config","namespace":"logging"}}
  creationTimestamp: "2025-03-25T10:25:17Z"
  name: fluentbit-custom-config
  namespace: logging
  resourceVersion: "939449"
  uid: bd3416e9-6700-4cd4-87b2-dcc610e17423
