apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-custom-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Parser docker
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name opensearch
        Match *
        Host ${OPENSEARCH_HOST}
        Port 443
        TLS On
        Index fluentbit
        AWS_Auth On
        AWS_Region us-east-1
        Logstash_Format On
        Replace_Dots On
        Retry_Limit False
        Suppress_Type_Name On