replicaCount: 1

service:
  type: ClusterIP
  port: 9090

serviceAccount:
  name: external-secrets-sa
  create: false

grafana:
  enabled: false

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - prometheus.imlinfo.xyz
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: alb
  prometheus:
  prometheusSpec:
    remoteWrite:
      - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
        basicAuth:
          username:
            name: prometheus-remote-write-secret
            key: username
          password:
            name: prometheus-remote-write-secret
            key: password
        writeRelabelConfigs:
          # ✅ Keep only "statuspage" namespace (your app)
          - sourceLabels: [namespace]
            regex: "statuspage"
            action: keep

          # 🔥 Drop everything else
          - action: drop
serviceMonitor:
  enabled: true
  namespace: statuspage
  selector:
    matchLabels:
      app: statuspage
  endpoints:
    - port: http
      path: /metrics